---
## Docs: https://defektive.github.io/xodbox/docs/pkg/handlers/
handlers:
  ## Docs: https://defektive.github.io/xodbox/docs/pkg/handlers/dns/
#  - handler: DNS
#    listener: 127.0.10.1:53
#    default_ip: 127.0.0.1
  ## Docs: https://defektive.github.io/xodbox/docs/pkg/handlers/httpx/
  - handler: HTTPX
#    payload_dir: payloads/httpx
#    static_dir: static
#    acme_email: youremail.real.place
#    acme_accept: false # this should be true. you must accept :D
#    acme_url: https://acme-staging-v02.api.letsencrypt.org/directory # when ready use real URL https://acme-v02.api.letsencrypt.org/directory
#    tls_names: "*.example.com,example.com"
#    dns_provider: namecheap # or route53
#    dns_provider_api_user: namecheap-user
#    dns_provider_api_key: namecheap-secret
    listener: :80
## Docs: https://defektive.github.io/xodbox/docs/pkg/notifiers/
notifiers:
#  ## Docs: https://defektive.github.io/xodbox/docs/pkg/notifiers/slack/
#  - notifier: slack
#    url: https://hooks.slack.com/services/T0...N
#    channel: general
#    author: PirateVirus
#    author_image: ':pirate:'
#    filter: "/l"
#  ## Docs: https://defektive.github.io/xodbox/docs/pkg/notifiers/discord/
#  - notifier: discord
#    url: https://discord.com/api/webhooks/133...6C
#    author: PirateVirus
#    author_image: https://s3-us-west-2.amazonaws.com/slack-f...72.png
#    filter: "/l"
  - notifier: app_log
